# This page lists all currencies supported by the API, and thus by this app

currencies = [
    "ILS - Israeli Shekel",
    "USD - United States Dollar",
    "EUR - Euro",
    "GBP - British Pound",
    "JPY - Japanese Yen",
    "BTC - Bitcoin",
    "AED - United Arab Emirates Dirham",
    "AFN - Afghan Afghani",
    "ALL - Albanian Lek",
    "AMD - Armenian Dram",
    "ANG - Netherlands Antillean Guilder",
    "AOA - Angolan Kwanza",
    "ARS - Argentine Peso",
    "AUD - Australian Dollar",
    "AWG - Aruban Florin",
    "AZN - Azerbaijani Manat",
    "BAM - Bosnia-Herzegovina Convertible Mark",
    "BBD - Barbadian Dollar",
    "BCH - Bitcoin Cash",
    "BDT - Bangladeshi Taka",
    "BGN - Bulgarian Lev",
    "BHD - Bahraini Dinar",
    "BIF - Burundian Franc",
    "BMD - Bermudian Dollar",
    "BND - Brunei Dollar",
    "BOB - Bolivian Boliviano",
    "BRL - Brazilian Real",
    "BSD - Bahamian Dollar",
    "BTG - Bitcoin Gold",
    "BWP - Botswana Pula",
    "BZD - Belize Dollar",
    "CAD - Canadian Dollar",
    "CDF - Congolese Franc",
    "CHF - Swiss Franc",
    "CLP - Chilean Peso",
    "CNH - Chinese Yuan (Offshore)",
    "CNY - Chinese Yuan",
    "COP - Colombian Peso",
    "CRC - Costa Rican Colon",
    "CUC - Cuban Convertible Peso",
    "CUP - Cuban Peso",
    "CVE - Cape Verdean Escudo",
    "CZK - Czech Koruna",
    "DASH - Dash",
    "DJF - Djiboutian Franc",
    "DKK - Danish Krone",
    "DOP - Dominican Peso",
    "DZD - Algerian Dinar",
    "EGP - Egyptian Pound",
    "EOS - EOS",
    "ETB - Ethiopian Birr",
    "ETH - Ethereum",
    "FJD - Fijian Dollar",
    "GEL - Georgian Lari",
    "GHS - Ghanaian Cedi",
    "GIP - Gibraltar Pound",
    "GMD - Gambian Dalasi",
    "GNF - Guinean Franc",
    "GTQ - Guatemalan Quetzal",
    "GYD - Guyanese Dollar",
    "HKD - Hong Kong Dollar",
    "HNL - Honduran Lempira",
    "HRK - Croatian Kuna",
    "HTG - Haitian Gourde",
    "HUF - Hungarian Forint",
    "IDR - Indonesian Rupiah",
    "INR - Indian Rupee",
    "IQD - Iraqi Dinar",
    "IRR - Iranian Rial",
    "ISK - Icelandic Krona",
    "JMD - Jamaican Dollar",
    "JOD - Jordanian Dinar",
    "KES - Kenyan Shilling",
    "KGS - Kyrgystani Som",
    "KHR - Cambodian Riel",
    "KMF - Comorian Franc",
    "KRW - South Korean Won",
    "KWD - Kuwaiti Dinar",
    "KYD - Cayman Islands Dollar",
    "KZT - Kazakhstani Tenge",
    "LAK - Lao Kip",
    "LBP - Lebanese Pound",
    "LKR - Sri Lankan Rupee",
    "LRD - Liberian Dollar",
    "LSL - Lesotho Loti",
    "LTC - Litecoin",
    "LYD - Libyan Dinar",
    "MAD - Moroccan Dirham",
    "MDL - Moldovan Leu",
    "MKD - Macedonian Denar",
    "MMK - Myanmar Kyat",
    "MOP - Macanese Pataca",
    "MUR - Mauritian Rupee",
    "MVR - Maldivian Rufiyaa",
    "MWK - Malawian Kwacha",
    "MXN - Mexican Peso",
    "MYR - Malaysian Ringgit",
    "MZN - Mozambican Metical",
    "NAD - Namibian Dollar",
    "NGN - Nigerian Naira",
    "NIO - Nicaraguan Córdoba",
    "NOK - Norwegian Krone",
    "NPR - Nepalese Rupee",
    "NZD - New Zealand Dollar",
    "OMR - Omani Rial",
    "PAB - Panamanian Balboa",
    "PEN - Peruvian Sol",
    "PGK - Papua New Guinean Kina",
    "PHP - Philippine Peso",
    "PKR - Pakistani Rupee",
    "PLN - Polish Zloty",
    "PYG - Paraguayan Guarani",
    "QAR - Qatari Rial",
    "RON - Romanian Leu",
    "RSD - Serbian Dinar",
    "RUB - Russian Ruble",
    "RWF - Rwandan Franc",
    "SAR - Saudi Riyal",
    "SBD - Solomon Islands Dollar",
    "SCR - Seychellois Rupee",
    "SDG - Sudanese Pound",
    "SEK - Swedish Krona",
    "SGD - Singapore Dollar",
    "SLL - Sierra Leonean Leone",
    "SOS - Somali Shilling",
    "SRD - Surinamese Dollar",
    "SVC - Salvadoran Colón",
    "SZL - Swazi Lilangeni",
    "THB - Thai Baht",
    "TJS - Tajikistani Somoni",
    "TMT - Turkmenistani Manat",
    "TND - Tunisian Dinar",
    "TOP - Tongan Paʻanga",
    "TRY - Turkish Lira",
    "TTD - Trinidad and Tobago Dollar",
    "TWD - New Taiwan Dollar",
    "TZS - Tanzanian Shilling",
    "UAH - Ukrainian Hryvnia",
    "UGX - Ugandan Shilling",
    "UYU - Uruguayan Peso",
    "UZS - Uzbekistani Som",
    "VND - Vietnamese Dong",
    "XAF - Central African CFA Franc",
    "XAG - Silver Ounce",
    "XAU - Gold Ounce",
    "XCD - East Caribbean Dollar",
    "XLM - Stellar Lumens",
    "XOF - West African CFA Franc",
    "XRP - Ripple",
    "YER - Yemeni Rial",
    "ZAR - South African Rand",
    "ZMW - Zambian Kwacha"
]